### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'lower'

### ISSUE THREAD

**Issue by gllmhyt** [jle64/gnome-pass-search-provider#34]
I have this error that makes the service fail to start since a few days. Here's the journal output:

```
systemd[1174]: Starting Pass and Bitwarden search provider for GNOME Shell daemon...
systemd[1174]: Started Pass and Bitwarden search provider for GNOME Shell daemon.
gnome-pass-search-provider.py[11832]: Traceback (most recent call last):
gnome-pass-search-provider.py[11832]:   File "/usr/lib/gnome-pass-search-provider/gnome-pass-search-provider.py", line 248, in <module>
gnome-pass-search-provider.py[11832]:     SearchPassService()
gnome-pass-search-provider.py[11832]:   File "/usr/lib/gnome-pass-search-provider/gnome-pass-search-provider.py", line 71, in __init__
gnome-pass-search-provider.py[11832]:     getenv("DISABLE_NOTIFICATIONS", False).lower() == "true"
gnome-pass-search-provider.py[11832]: AttributeError: 'bool' object has no attribute 'lower'
systemd[1174]: org.gnome.Pass.SearchProvider.service: Main process exited, code=exited, status=1/FAILURE
systemd[1174]: org.gnome.Pass.SearchProvider.service: Failed with result 'exit-code'.
```

Fixed with #33

**Comment by jle64** [comment]
Thanks for reporting this, I merged #33 so this should be fixed.
